### PR TITLE
Require Formula explicitly

### LINKED ISSUE #31: undefined method `[]' for Formula:Clas
Hello,
I am using MacOS 11 and get the following error message when executing the script:

```
brew autoupdate --start 86400 --enable-notification
Error: undefined method `[]' for Formula:Class
/usr/local/Homebrew/Library/Taps/domt4/homebrew-autoupdate/lib/autoupdate/notify.rb:6:in `notifier'
/usr/local/Homebrew/Library/Taps/domt4/homebrew-autoupdate/lib/autoupdate/start.rb:25:in `start'
/usr/local/Homebrew/Library/Taps/domt4/homebrew-autoupdate/cmd/brew-autoupdate.rb:35:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:85:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:115:in `<main>'
```

### PR DESCRIPTION
**Pull request by agross**
Closes #31

### CODE REVIEW

**Comment by DomT4** [comment]
Thank you @agross. Sorry for the wait on this, and generally the quiet couple months here. As I noted in another PR just now, I had a lot of internet issues after moving house, which shouldn't be an issue going forwards.

**Comment by BrianAMartin221** [comment]
Hey, no need to apologize when providing a free open source tool!

I'm having what seems like an odd issue I have 3 machines that I use Homebrew on
2 x on Catalina 
1 x on Mojave.  One of the Catalina machines has been running as expected for months with your Tap. It updates homebrew every 8 hours and I get a notification.   

For some reason a few weeks ago it stopped running currently on my Mojave and the other Catalina machine. I ended up uninstalling Homebrew on both of them, re-installing all of my brew items, and re-installing brew autoupdate, that's when I noticed the notifications were coming through. I tried running the script daisy changed without the "enable-notification" and then running that by itself but still no notifications. When I run the status command it says autoupdate is installed and running but if I wait a day and run brew update myself I always seem to have a few updates. 

So I have a feeling its not running correctly which is more than likely of my doing. But let me know if there is any other de-bugging or command I could run to try and fix the issue.

**Comment by DomT4** [comment]
There should be logging in `~/Library/Logs/com.github.domt4.homebrew-autoupdate`, one for regular output and the other for error logging. Could be worth taking a peek in there to see if there's anything noticeable.

I'm hoping to get some time Sunday to generally catch up on some of the changes Homebrew has made and the resulting questions posed in various PRs/Issues in this tap, as well as generally thinking a bit more about my prior design choices on different aspects. This tap was designed to be a very low maintenance code base with very few "moving parts" as it were so there'd be minimal breakage regardless of whatever direction Homebrew pushed itself in over time, but that logic hasn't proven 100% flawless.

**Comment by BrianAMartin221** [comment]
I tried to take a look at the log but wasn't even sure what program to open them with to read it.

**Comment by agross** [comment]
@BrianAMartin221 `cat`, `less` and `tail` will do. You can leave `tail -f <file>` running in a terminal and it'll update as soon as the file is written to.

**Comment by BrianAMartin221** [comment]
> @BrianAMartin221 `cat`, `less` and `tail` will do. You can leave `tail -f <file>` running in a terminal and it'll update as soon as the file is written to.

I haven't run commands like that before in terminal, I'll look into it today thanks!

**Pull request merged**
